spring:
  application:
    name: web-flux-app
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8874

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true